### PR TITLE
Strict Tab Control

### PR DESCRIPTION
**Pull request by AceCoderLaura**
Hey, I had the same problem with the SelectedValue of a TabControl in my application so I tried applying the same strategy employed with the StrictComboBox to create a StrictTabControl.
It solved the issue in my application so let me know what you think! I'm not too sure about some parts, I feel like I should use a separate bool value for the different properties but it works either way, but definitely make any amendments you feel are a good idea!

### CODE REVIEW

**Comment by AceCoderLaura** [comment]
I just found a bug in this new control. I'll let you know when it's fixed.

**Comment by AceCoderLaura** [comment]
Okay I think I fixed it.

**Comment by michaellperry** [comment]
Thank you so much for this contribution! Let me fire it up this weekend and check it out.

**Comment by michaellperry** [comment]
I made one minor change. I'm glad that you were able to simplify the fix to the selected value bug. That first attempt looked like it might not always work.

I think you made the right choice having a single pair of Booleans for both properties. Data flow is always in from the user or out from the application, even if multiple properties are involved. And these two properties are so closely linked that they had to interact.

Thanks for this contribution. I hadn't run into this problem before. I hope others will find it helpful.

**Pull request merged**
